import * as React from "react"

function SvgComponent(props: any) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path d="M24 24H0V0h24v24z" fill="none" />
      <circle cx={12} cy={12} r={8} />
    </svg>
  )
}

export default SvgComponent

//material-ui fiber_manual_record icon https://material.io/resources/icons/?icon=fiber_manual_record&style=baseline
//component generated by svgr https://github.com/gregberge/svgr
